kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-argocd-application-controller-role
  namespace: phpinfo-helm-lourdes
rules:
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - services
      - deployments
